/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v4.1
processor: MK28FN2M0xxx15
package_id: MK28FN2M0VMI15
mcu_data: ksdk2_0
processor_version: 4.0.0
pin_labels:
- {pin_num: K9, pin_signal: ADC0_SE11/PTA8/I2C1_SCL/FTM1_CH0/FTM1_QD_PHA/TPM1_CH0/TRACE_D2, label: Reset, identifier: RESET}
- {pin_num: K10, pin_signal: PTA9/I2C1_SDA/FTM1_CH1/FTM1_QD_PHB/TPM1_CH1/TRACE_D1, label: Interrupt, identifier: INTERRUPT}
- {pin_num: E3, pin_signal: PTE7/FXIO0_D13/LPUART3_RTS_b/I2S0_RXD0/QSPI0B_SCLK/FTM3_CH2/QSPI0A_SS1_B, label: Interrupt, identifier: INTERRUPT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: K13, peripheral: SPI0, signal: PCS0_SS, pin_signal: PTA14/SPI0_PCS0/LPUART0_TX/TRACE_D2/FXIO0_D20/I2S0_RX_BCLK/I2S0_TXD1}
  - {pin_num: K12, peripheral: SPI0, signal: SCK, pin_signal: PTA15/SPI0_SCK/LPUART0_RX/TRACE_D1/FXIO0_D21/I2S0_RXD0}
  - {pin_num: J13, peripheral: SPI0, signal: SOUT, pin_signal: PTA16/SPI0_SOUT/LPUART0_CTS_b/TRACE_D0/FXIO0_D22/I2S0_RX_FS/I2S0_RXD1}
  - {pin_num: J12, peripheral: SPI0, signal: SIN, pin_signal: PTA17/SPI0_SIN/LPUART0_RTS_b/FXIO0_D23/I2S0_MCLK/I2S1_MCLK}
  - {pin_num: C2, peripheral: SPI2, signal: PCS0_SS, pin_signal: PTD11/LLWU_P25/SPI2_PCS0/LPUART1_CTS_b/FB_A19/FXIO0_D27}
  - {pin_num: B2, peripheral: SPI2, signal: SCK, pin_signal: PTD12/SPI2_SCK/FTM3_FLT0/FB_A20/FXIO0_D28}
  - {pin_num: B3, peripheral: SPI2, signal: SOUT, pin_signal: PTD13/SPI2_SOUT/FB_A21/FXIO0_D29}
  - {pin_num: A2, peripheral: SPI2, signal: SIN, pin_signal: PTD14/SPI2_SIN/FB_A22/FXIO0_D30}
  - {pin_num: A7, peripheral: LPUART0, signal: RX, pin_signal: PTC25/LPUART0_RX/FB_A4/SDRAM_D4/QSPI0A_SCLK}
  - {pin_num: B7, peripheral: LPUART0, signal: TX, pin_signal: PTC24/LPUART0_TX/FB_A5/SDRAM_D5/QSPI0A_DATA3}
  - {pin_num: K9, peripheral: GPIOA, signal: 'GPIO, 8', pin_signal: ADC0_SE11/PTA8/I2C1_SCL/FTM1_CH0/FTM1_QD_PHA/TPM1_CH0/TRACE_D2, direction: OUTPUT, gpio_init_state: 'false'}
  - {pin_num: K10, peripheral: GPIOA, signal: 'GPIO, 9', pin_signal: PTA9/I2C1_SDA/FTM1_CH1/FTM1_QD_PHB/TPM1_CH1/TRACE_D1, direction: INPUT, gpio_interrupt: kPORT_InterruptLogicOne}
  - {pin_num: J10, peripheral: SDHC, signal: DCLK, pin_signal: PTA26/LPUART2_CTS_b/SDHC0_DCLK/FB_A13/SDRAM_D13/FB_A27/I2S1_TXD0, pull_select: up, pull_enable: enable}
  - {pin_num: H11, peripheral: SDHC, signal: 'D, 2', pin_signal: PTA29/LPUART3_RX/SDHC0_D2/FB_A24/I2S1_RXD0, pull_select: up, pull_enable: enable}
  - {pin_num: J11, peripheral: SDHC, signal: 'D, 0', pin_signal: PTA25/LPUART2_RX/SDHC0_D0/FB_A14/SDRAM_D14/FB_A28/I2S1_TX_FS, pull_select: up, pull_enable: enable}
  - {pin_num: K11, peripheral: SDHC, signal: 'D, 1', pin_signal: PTA24/LPUART2_TX/SDHC0_D1/FB_A15/SDRAM_D15/FB_A29/I2S1_TX_BCLK, pull_select: up, pull_enable: enable}
  - {pin_num: H12, peripheral: SDHC, signal: 'D, 3', pin_signal: PTA28/LPUART3_TX/SDHC0_D3/FB_A25/I2S1_RXD1, pull_select: up, pull_enable: enable}
  - {pin_num: H13, peripheral: SDHC, signal: CMD, pin_signal: PTA27/LPUART2_RTS_b/SDHC0_CMD/FB_A12/SDRAM_D12/FB_A26/I2S1_TXD1, pull_select: up, pull_enable: enable}
  - {pin_num: F13, peripheral: GPIOB, signal: 'GPIO, 5', pin_signal: PTB5/FTM2_FLT0, pull_select: up, pull_enable: enable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
#if 0
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);

    gpio_pin_config_t RESET_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA8 (pin K9)  */
    GPIO_PinInit(BOARD_INITPINS_RESET_GPIO, BOARD_INITPINS_RESET_PIN, &RESET_config);

    gpio_pin_config_t INTERRUPT_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA9 (pin K10)  */
    GPIO_PinInit(BOARD_INITPINS_INTERRUPT_GPIO, BOARD_INITPINS_INTERRUPT_PIN, &INTERRUPT_config);

    /* PORTA14 (pin K13) is configured as SPI0_PCS0 */
    PORT_SetPinMux(PORTA, 14U, kPORT_MuxAlt2);

    /* PORTA15 (pin K12) is configured as SPI0_SCK */
    PORT_SetPinMux(PORTA, 15U, kPORT_MuxAlt2);

    /* PORTA16 (pin J13) is configured as SPI0_SOUT */
    PORT_SetPinMux(PORTA, 16U, kPORT_MuxAlt2);

    /* PORTA17 (pin J12) is configured as SPI0_SIN */
    PORT_SetPinMux(PORTA, 17U, kPORT_MuxAlt2);

    /* PORTA24 (pin K11) is configured as SDHC0_D1 */
    PORT_SetPinMux(PORTA, 24U, kPORT_MuxAlt4);

    PORTA->PCR[24] = ((PORTA->PCR[24] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTA25 (pin J11) is configured as SDHC0_D0 */
    PORT_SetPinMux(PORTA, 25U, kPORT_MuxAlt4);

    PORTA->PCR[25] = ((PORTA->PCR[25] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTA26 (pin J10) is configured as SDHC0_DCLK */
    PORT_SetPinMux(PORTA, 26U, kPORT_MuxAlt4);

    PORTA->PCR[26] = ((PORTA->PCR[26] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTA27 (pin H13) is configured as SDHC0_CMD */
    PORT_SetPinMux(PORTA, 27U, kPORT_MuxAlt4);

    PORTA->PCR[27] = ((PORTA->PCR[27] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTA28 (pin H12) is configured as SDHC0_D3 */
    PORT_SetPinMux(PORTA, 28U, kPORT_MuxAlt4);

    PORTA->PCR[28] = ((PORTA->PCR[28] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTA29 (pin H11) is configured as SDHC0_D2 */
    PORT_SetPinMux(PORTA, 29U, kPORT_MuxAlt4);

    PORTA->PCR[29] = ((PORTA->PCR[29] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTA8 (pin K9) is configured as PTA8 */
    PORT_SetPinMux(BOARD_INITPINS_RESET_PORT, BOARD_INITPINS_RESET_PIN, kPORT_MuxAsGpio);

    /* PORTA9 (pin K10) is configured as PTA9 */
    PORT_SetPinMux(BOARD_INITPINS_INTERRUPT_PORT, BOARD_INITPINS_INTERRUPT_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTA9 (pin K10): Interrupt when logic one */
    PORT_SetPinInterruptConfig(BOARD_INITPINS_INTERRUPT_PORT, BOARD_INITPINS_INTERRUPT_PIN, kPORT_InterruptLogicOne);

    /* PORTB5 (pin F13) is configured as PTB5 */
    PORT_SetPinMux(PORTB, 5U, kPORT_MuxAsGpio);

    PORTB->PCR[5] = ((PORTB->PCR[5] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTC24 (pin B7) is configured as LPUART0_TX */
    PORT_SetPinMux(PORTC, 24U, kPORT_MuxAlt3);

    /* PORTC25 (pin A7) is configured as LPUART0_RX */
    PORT_SetPinMux(PORTC, 25U, kPORT_MuxAlt3);

    /* PORTD11 (pin C2) is configured as SPI2_PCS0 */
    PORT_SetPinMux(PORTD, 11U, kPORT_MuxAlt2);

    /* PORTD12 (pin B2) is configured as SPI2_SCK */
    PORT_SetPinMux(PORTD, 12U, kPORT_MuxAlt2);

    /* PORTD13 (pin B3) is configured as SPI2_SOUT */
    PORT_SetPinMux(PORTD, 13U, kPORT_MuxAlt2);

    /* PORTD14 (pin A2) is configured as SPI2_SIN */
    PORT_SetPinMux(PORTD, 14U, kPORT_MuxAlt2);

    SIM->SOPT5 = ((SIM->SOPT5 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT5_LPUART0TXSRC_MASK | SIM_SOPT5_LPUART0RXSRC_MASK)))

                  /* LPUART0 transmit data source select: LPUART0_TX pin. */
                  | SIM_SOPT5_LPUART0TXSRC(SOPT5_LPUART0TXSRC_LPUART_TX)

                  /* LPUART0 receive data source select: LPUART0_RX pin. */
                  | SIM_SOPT5_LPUART0RXSRC(SOPT5_LPUART0RXSRC_LPUART_RX));
}
#else
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);

//! Adding 2 GPIO pins for Power save
    //! MCU-PIN2 - freedom-PIND10->output PIN
    //! MCU-PIN3 - freedom-PIND15->Input PIN
    /*
    -------------------------------------
	|MCU PIN|freedom board PIN |Direction|
	--------------------------------------
	|   2   |      PIND10      |  Output |
	|   3   |      PIND15      |  Input  |
	--------------------------------------
	*/

	gpio_pin_config_t PS_out_config = {
			.pinDirection = kGPIO_DigitalOutput,
			.outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA8 (pin K9)  */
    GPIO_PinInit(BOARD_INITPINS_PS_OUT_GPIO, BOARD_INITPINS_PS_OUT_PIN , &PS_out_config);

    /* PORTA8 (pin K9) is configured as PTA8 */
    PORT_SetPinMux(BOARD_INITPINS_PS_OUT_PORT, BOARD_INITPINS_PS_OUT_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[10] = ((PORTD->PCR[10] &
    		/* Mask bits to zero which are setting */
    		(~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

    		/* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
    		 * corresponding PE field is set. */
    		| (uint32_t)(kPORT_PullDown));


    gpio_pin_config_t PS_in_config = {

    		.pinDirection = kGPIO_DigitalInput,
			.outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA8 (pin K9)  */
    GPIO_PinInit(BOARD_INITPINS_PS_IN_GPIO, BOARD_INITPINS_PS_IN_PIN , &PS_in_config);

    /* PORTA8 (pin K9) is configured as PTA8 */
    PORT_SetPinMux(BOARD_INITPINS_PS_IN_PORT, BOARD_INITPINS_PS_IN_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[15] = ((PORTD->PCR[15] &
    		/* Mask bits to zero which are setting */
    		(~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

    		/* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
    		 * corresponding PE field is set. */
    		| (uint32_t)(kPORT_PullDown));
			
    gpio_pin_config_t RESET_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };

    /* Initialize GPIO functionality on pin PTD14  */
    GPIO_PinInit(BOARD_INITPINS_RESET_GPIO, BOARD_INITPINS_RESET_PIN, &RESET_config);

    /* PORTD14 is configured as PTD14 */
    PORT_SetPinMux(BOARD_INITPINS_RESET_PORT, BOARD_INITPINS_RESET_PIN, kPORT_MuxAsGpio);

    gpio_pin_config_t INTERRUPT_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };


    /* Interrupt configuration on PORTD9 (pin K10): Interrupt when logic one */
#if WIFI_TCP_BI_DIR
    PORT_SetPinInterruptConfig(BOARD_INITPINS_INTERRUPT_PORT, BOARD_INITPINS_INTERRUPT_PIN, kPORT_InterruptLogicOne);
#else
    PORT_SetPinInterruptConfig(BOARD_INITPINS_INTERRUPT_PORT, BOARD_INITPINS_INTERRUPT_PIN, kPORT_InterruptRisingEdge);
#endif


    /* Initialize GPIO functionality on pin PTA9 (pin K10)  */
     GPIO_PinInit(BOARD_INITPINS_INTERRUPT_GPIO, BOARD_INITPINS_INTERRUPT_PIN, &INTERRUPT_config);

#if 1
    PORTD->PCR[9] = ((PORTD->PCR[9] &
                           /* Mask bits to zero which are setting */
                           (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                          /* Pull Select: Internal pullup resistor is disabled on the corresponding pin, if the
                           * corresponding PE field is clear. */
                          | (uint32_t)(kPORT_PullDown));
#endif

    /* PORTA9 (pin K10) is configured as PTA9 */
    PORT_SetPinMux(BOARD_INITPINS_INTERRUPT_PORT, BOARD_INITPINS_INTERRUPT_PIN, kPORT_MuxAsGpio);

    /* PORTA14 (pin K13) is configured as SPI0_PCS0 */
    PORT_SetPinMux(PORTA, 14U, kPORT_MuxAlt2);

    /* PORTA15 (pin K12) is configured as SPI0_SCK */
    PORT_SetPinMux(PORTA, 15U, kPORT_MuxAlt2);

    /* PORTA16 (pin J13) is configured as SPI0_SOUT */
    PORT_SetPinMux(PORTA, 16U, kPORT_MuxAlt2);

    /* PORTA17 (pin J12) is configured as SPI0_SIN */
    PORT_SetPinMux(PORTA, 17U, kPORT_MuxAlt2);

    /* PORTA24 (pin K11) is configured as SDHC0_D1 */
    PORT_SetPinMux(PORTA, 24U, kPORT_MuxAlt4);

    PORTA->PCR[24] = ((PORTA->PCR[24] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTA25 (pin J11) is configured as SDHC0_D0 */
    PORT_SetPinMux(PORTA, 25U, kPORT_MuxAlt4);

    PORTA->PCR[25] = ((PORTA->PCR[25] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTA26 (pin J10) is configured as SDHC0_DCLK */
    PORT_SetPinMux(PORTA, 26U, kPORT_MuxAlt4);

    PORTA->PCR[26] = ((PORTA->PCR[26] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTA27 (pin H13) is configured as SDHC0_CMD */
    PORT_SetPinMux(PORTA, 27U, kPORT_MuxAlt4);

    PORTA->PCR[27] = ((PORTA->PCR[27] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTA28 (pin H12) is configured as SDHC0_D3 */
    PORT_SetPinMux(PORTA, 28U, kPORT_MuxAlt4);

    PORTA->PCR[28] = ((PORTA->PCR[28] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTA29 (pin H11) is configured as SDHC0_D2 */
    PORT_SetPinMux(PORTA, 29U, kPORT_MuxAlt4);

    PORTA->PCR[29] = ((PORTA->PCR[29] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp));


    /* PORTB5 (pin F13) is configured as PTB5 */
    PORT_SetPinMux(PORTB, 5U, kPORT_MuxAsGpio);

    PORTB->PCR[5] = ((PORTB->PCR[5] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTC24 (pin B7) is configured as LPUART0_TX */
    PORT_SetPinMux(PORTC, 24U, kPORT_MuxAlt3);

    /* PORTC25 (pin A7) is configured as LPUART0_RX */
    PORT_SetPinMux(PORTC, 25U, kPORT_MuxAlt3);

    SIM->SOPT5 = ((SIM->SOPT5 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT5_LPUART0TXSRC_MASK | SIM_SOPT5_LPUART0RXSRC_MASK)))

                  /* LPUART0 transmit data source select: LPUART0_TX pin. */
                  | SIM_SOPT5_LPUART0TXSRC(SOPT5_LPUART0TXSRC_LPUART_TX)

                  /* LPUART0 receive data source select: LPUART0_RX pin. */
                  | SIM_SOPT5_LPUART0RXSRC(SOPT5_LPUART0RXSRC_LPUART_RX));

    //! SDRAM pins
    /* PORTB0 (pin G13) is configured as SDRAM_CAS_b */
        PORT_SetPinMux(PORTB, 0U, kPORT_MuxAlt5);

        /* PORTB1 (pin G12) is configured as SDRAM_RAS_b */
        PORT_SetPinMux(PORTB, 1U, kPORT_MuxAlt5);

        /* PORTB10 (pin G9) is configured as SDRAM_D19 */
        PORT_SetPinMux(PORTB, 10U, kPORT_MuxAlt5);

        /* PORTB11 (pin E13) is configured as SDRAM_D18 */
        PORT_SetPinMux(PORTB, 11U, kPORT_MuxAlt5);

        /* PORTB16 (pin F8) is configured as SDRAM_D17 */
        PORT_SetPinMux(PORTB, 16U, kPORT_MuxAlt5);

        /* PORTB17 (pin D13) is configured as SDRAM_D16 */
        PORT_SetPinMux(PORTB, 17U, kPORT_MuxAlt5);

        /* PORTB18 (pin D12) is configured as SDRAM_A23 */
        PORT_SetPinMux(PORTB, 18U, kPORT_MuxAlt5);

        /* PORTB2 (pin G11) is configured as SDRAM_WE_b */
        PORT_SetPinMux(PORTB, 2U, kPORT_MuxAlt5);

        /* PORTB20 (pin D10) is configured as SDRAM_D31 */
        PORT_SetPinMux(PORTB, 20U, kPORT_MuxAlt5);

        /* PORTB21 (pin D9) is configured as SDRAM_D30 */
        PORT_SetPinMux(PORTB, 21U, kPORT_MuxAlt5);

        /* PORTB22 (pin C13) is configured as SDRAM_D29 */
        PORT_SetPinMux(PORTB, 22U, kPORT_MuxAlt5);

        /* PORTB23 (pin C12) is configured as SDRAM_D28 */
        PORT_SetPinMux(PORTB, 23U, kPORT_MuxAlt5);

        /* PORTB3 (pin G10) is configured as SDRAM_CS0_b */
        PORT_SetPinMux(PORTB, 3U, kPORT_MuxAlt5);

        /* PORTB6 (pin F12) is configured as SDRAM_D23 */
        PORT_SetPinMux(PORTB, 6U, kPORT_MuxAlt5);

        /* PORTB7 (pin F11) is configured as SDRAM_D22 */
        PORT_SetPinMux(PORTB, 7U, kPORT_MuxAlt5);

        /* PORTB8 (pin F10) is configured as SDRAM_D21 */
        PORT_SetPinMux(PORTB, 8U, kPORT_MuxAlt5);

        /* PORTB9 (pin F9) is configured as SDRAM_D20 */
        PORT_SetPinMux(PORTB, 9U, kPORT_MuxAlt5);

        /* PORTC0 (pin B13) is configured as SDRAM_A22 */
        PORT_SetPinMux(PORTC, 0U, kPORT_MuxAlt5);

        /* PORTC1 (pin B12) is configured as SDRAM_A21 */
        PORT_SetPinMux(PORTC, 1U, kPORT_MuxAlt5);

        /* PORTC10 (pin A8) is configured as SDRAM_A13 */
        PORT_SetPinMux(PORTC, 10U, kPORT_MuxAlt5);

        /* PORTC12 (pin B9) is configured as SDRAM_D27 */
        PORT_SetPinMux(PORTC, 12U, kPORT_MuxAlt5);

        /* PORTC13 (pin B8) is configured as SDRAM_D26 */
        PORT_SetPinMux(PORTC, 13U, kPORT_MuxAlt5);

        /* PORTC14 (pin C8) is configured as SDRAM_D25 */
        PORT_SetPinMux(PORTC, 14U, kPORT_MuxAlt5);

        /* PORTC15 (pin D8) is configured as SDRAM_D24 */
        PORT_SetPinMux(PORTC, 15U, kPORT_MuxAlt5);

        /* PORTC16 (pin E8) is configured as SDRAM_DQM2 */
        PORT_SetPinMux(PORTC, 16U, kPORT_MuxAlt5);

        /* PORTC17 (pin E7) is configured as SDRAM_DQM3 */
        PORT_SetPinMux(PORTC, 17U, kPORT_MuxAlt5);

        /* PORTC2 (pin A13) is configured as SDRAM_A20 */
        PORT_SetPinMux(PORTC, 2U, kPORT_MuxAlt5);

        /* PORTC3 (pin A12) is configured as CLKOUT */
        PORT_SetPinMux(PORTC, 3U, kPORT_MuxAlt5);

        /* PORTC4 (pin B11) is configured as SDRAM_A19 */
        PORT_SetPinMux(PORTC, 4U, kPORT_MuxAlt5);

        /* PORTC5 (pin A11) is configured as SDRAM_A18 */
        PORT_SetPinMux(PORTC, 5U, kPORT_MuxAlt5);

        /* PORTC7 (pin B10) is configured as SDRAM_A16 */
        PORT_SetPinMux(PORTC, 7U, kPORT_MuxAlt5);

        /* PORTC8 (pin C10) is configured as SDRAM_A15 */
        PORT_SetPinMux(PORTC, 8U, kPORT_MuxAlt5);

        /* PORTC9 (pin C9) is configured as SDRAM_A14 */
        PORT_SetPinMux(PORTC, 9U, kPORT_MuxAlt5);

        /* PORTD2 (pin A4) is configured as SDRAM_A12 */
        PORT_SetPinMux(PORTD, 2U, kPORT_MuxAlt5);

        /* PORTD3 (pin B4) is configured as SDRAM_A11 */
        PORT_SetPinMux(PORTD, 3U, kPORT_MuxAlt5);

        /* PORTD4 (pin B5) is configured as SDRAM_A10 */
        PORT_SetPinMux(PORTD, 4U, kPORT_MuxAlt5);

        /* PORTD5 (pin C4) is configured as SDRAM_A9 */
        PORT_SetPinMux(PORTD, 5U, kPORT_MuxAlt5);

        /* PORTD7 (pin E5) is configured as SDRAM_CKE */
        PORT_SetPinMux(PORTD, 7U, kPORT_MuxAlt5);
}
#endif
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
