/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_
#include "MK28F15.h"
/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_LPUART0RXSRC_LPUART_RX 0x00u /*!<@brief LPUART0 receive data source select: LPUART0_RX pin */
#define SOPT5_LPUART0TXSRC_LPUART_TX 0x00u /*!<@brief LPUART0 transmit data source select: LPUART0_TX pin */

#if 0
/*! @name PORTA8 (coord K9), Reset
  @{ */
#define BOARD_INITPINS_RESET_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_RESET_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_RESET_PIN 8U     /*!<@brief PORTA pin index: 8 */
                                        /* @} */
#else
/*! @name PORTD14 (coord K9), Reset
  @{ */
#define BOARD_INITPINS_RESET_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_RESET_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_RESET_PIN 14U     /*!<@brief PORTA pin index: 14 */
                                        /* @} */
#endif
#if 0
/*! @name PORTA9 (coord K10), Interrupt
  @{ */
#define BOARD_INITPINS_INTERRUPT_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_INTERRUPT_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_INTERRUPT_PIN 9U     /*!<@brief PORTA pin index: 9 */
                                            /* @} */
#endif

#define BOARD_INITPINS_INTERRUPT_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_INTERRUPT_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_INTERRUPT_PIN 9U     /*!<@brief PORTA pin index: 9 */
                                            /* @} */

#define BOARD_INITPINS_PS_OUT_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_PS_OUT_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_PS_OUT_PIN 10U     /*!<@brief PORTD pin index: 10 */
                                        /* @} */

#define BOARD_INITPINS_PS_IN_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_PS_IN_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_PS_IN_PIN 15U     /*!<@brief PORTD pin index: 15 */
                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
